Hotel/urls.py
from django.urls import path

from .views import *

app_name= 'Hotel'

urlpatterns = [
    path("",home,name='home'),
    path("hotel/<slug>",hotel_detail,name='hotel_detail'),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>",room_type_detail,name="room_type_detail"),
    path("selected_rooms/",selected_rooms,name="selected_rooms"),
    path("checkout/<booking_id>/",checkout,name="checkout"),
    path("update_room_status/",update_room_status,name="update_room_status"),
    



    #payments routes 
    path("api/create_checkout_session/<booking_id>/",create_checkout_session,name='api_checkout_session'),
    path('success/<booking_id>/',payment_success, name='success'),
    path('failed/<booking_id>/',payment_failed, name='failed'),
]

UserAuth/urls.py
from django.urls import path

from .views import *

app_name= 'UserAuth'

urlpatterns = [
    path("sign-up",registerView,name='sign-up'),
    path("sign-in",loginViewTemp,name='sign-in'),
    path("logout",logoutView,name='logout'),
]

User_dashboard/urls.py
from django.urls import path 
from .views import *

app_name="user_dashboard"

urlpatterns = [
    path("",dasboard,name="dashboard"),
    path("bookings/",bookings,name="bookings"),
    path("notifications/",notifications ,name="notifications"),
    path("mark_as_read/<id>/",mark_as_read ,name="mark_as_read"),
    path("booking_details/<booking_id>",booking_details,name="booking_details")
]

travel_booking_platform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Hotel import views as hotel_views
from django.conf import settings


from django.conf.urls.static import static


urlpatterns = [ 
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin/', admin.site.urls),
    path("",hotel_views.home,name="home"),

    # custom urls
    # userauth urls
    path('user/',include("UserAuth.urls")),

    # hotel ursl
    path('',include("Hotel.urls")),

    # booking ursl
    path('booking/',include("booking.urls")),

    # booking ursl
    path('dashboard/',include("User_dashboard.urls")),


    # ckeditor ursl
    path('ckeditor5/',include("django_ckeditor_5.urls")),


    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

Hotel/views.py
from decimal import Decimal
import json
from django.http import HttpResponseBadRequest, JsonResponse
from django.conf import settings
from django.shortcuts import *
from UserAuth.models import User 
from django.utils import timezone
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages
from datetime import datetime as dt
import stripe


from .models import *
# Create your views here.
def home(request):
    hotels = Hotel.objects.filter(status="Live") 

    context = {
        "hotels":hotels
    }
    return render(request,"hotel/index.html",context) 


def hotel_detail(request,slug):
    hotel = Hotel.objects.get(slug=slug)
    rtype=RoomType.objects.filter(hotel=hotel,)

    context = {
        "hotel":hotel, 
        "rtype":rtype
    }
    return render(request,"hotel/hotel_page.html",context) 



def room_type_detail(request,slug,rt_slug): 
    hotel=Hotel.objects.get(slug=slug) 
    room_type=RoomType.objects.get(hotel=hotel,slug=rt_slug)
    rtype=RoomType.objects.filter(hotel=hotel,)
    rooms= Room.objects.filter(room_type=room_type,is_available=True)


    id = request.GET.get("hotel-id")
    checkin = request.GET.get("checkin")
    checkout = request.GET.get("checkout")
    adults = request.GET.get("adults")
    children = request.GET.get("children")

    context = {  
        "hotel":hotel, 
        "room_type":room_type, 
        "rtype":rtype,          
        "checkin":checkin, 
        "checkout":checkout, 
        "adults":adults, 
        "children":children, 
        "rooms":rooms
    }

    return render(request,"hotel/room_type_detail.html",context)

def selected_rooms(request):
    # context = {}
    total=0
    total_usd=0
    room_count=0
    total_days=0
    adults=0
    children=0
    checkin=""
    checkout=""
    user=None 
    if request.user.is_authenticated:
        user= request.user
    # room_type=None

    if "selection_data_obj" in request.session:
        hotel = None

        if request.method == "POST":
            for h_id,items in request.session['selection_data_obj'].items():
                id= int(items['hotel_id'])
                checkin= items['checkin']
                checkout= items['checkout']
                adults= int(items['adults']) if not None else 0
                children= int(items['children']) if not None else 0
                room_type_= int(items['room_type'])
                room_id= int(items['room_id'])\
                
                user = user

                hotel = Hotel.objects.get(id=id)
                room = Room.objects.get(id=room_id)
                room_type = RoomType.objects.get(id=room_type_)

            # date_format = "%Y-%m-%d"
            checkin_date = dt.strptime(checkin, "%Y-%m-%d")
            checkout_date = dt.strptime(checkout, "%Y-%m-%d")
            time_difference = checkout_date - checkin_date

            total_days = time_difference.days

            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            email = request.POST.get('email')
            phone = request.POST.get('phone')

            booking = Booking.objects.create(
                hotel=hotel,
                room_type=room_type,
                checkin_date=checkin,
                checkout_date=checkout,
                total_days=total_days,
                num_adults=adults,
                num_children=children,
                fullname=firstname +" "+lastname,
                email=email,
                phone=phone,  
                payment_status = "Processing",

                user = user          
            )
            for h_id,items in request.session['selection_data_obj'].items():
                room_id = int(items['room_id'])
                room = Room.objects.get(id=room_id)
                booking.room.add(room)

                room_count +=1
                days = total_days
                price = int(room_type.price)                
                room_price = price*room_count 
                total = room_price*days

            booking.total += float(total)
            booking.before_discount += float(total)
            booking.save()

            return redirect("Hotel:checkout",booking.booking_id)

        
        for h_id,items in request.session['selection_data_obj'].items():
            id= int(items['hotel_id'])
            checkin= items['checkin']
            checkout= items['checkout']
            adults= int(items['adults']) if not None else 0
            children= int(items['children']) if not None else 0
            room_type_= int(items['room_type'])
            room_id= int(items['room_id'])


            room_type = RoomType.objects.get(id=room_type_)

            checkin_date = dt.strptime(checkin, "%Y-%m-%d")
            checkout_date = dt.strptime(checkout, "%Y-%m-%d")
            time_difference = checkout_date - checkin_date

            total_days = time_difference.days
            room_count +=1
            days = total_days
            price = int(room_type.price)
            # room_name_= room_type.type
            # room_type=room_name_
            room_price = price*room_count 
            total = room_price*days
            total_usd=total/145

            hotel = Hotel.objects.get(id=id)
            
        context = {
            "data": request.session['selection_data_obj'],
            "total_selected_item": len(request.session['selection_data_obj']),
            # "room_name":room_type,
            "total":total,
            "total_days":total_days,
            "adults":adults,
            "children":children,
            "checkin":checkin,
            "checkout":checkout,
            "hotel":hotel,
        }

        return render(request,"hotel/selected_rooms.html",context)

            
    else:
        return redirect("/")
    # return render(request,"hotel/selected_rooms.html",context)
    

def checkout(request,booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    # total_usd = 0
    if request.method == "POST":
        code = request.POST.get("code")
        try:
            coupon = Coupon.objects.get(code__iexact=code,active=True)
            if coupon in booking.coupons.all():
                messages.warning(request,"Coupon already Activated!")
                return redirect('Hotel:checkout',booking.booking_id)
            else:
                if coupon.type == "Percentage":
                    discount = booking.total* coupon.discount / 100
                else: 
                    discount = coupon.discount
                
                booking.coupons.add(coupon)
                booking.total -= discount
                booking.saved += discount
                booking.payment_status = "Processing"
                booking.is_active=True
                booking.save()                
                coupon.redemptions +=1
                coupon.save()
                
                print("US Dollars equivalent to your amount is : ",total_usd )

                messages.success(request, "Coupon Activated!")
                return redirect('Hotel:checkout',booking.booking_id)
        except: 
            messages.error(request,"Coupon Does Not Exist")
    usd = float(booking.total)/145
    total_usd= "%.2f" %usd
    context = {
        "booking":booking,
        "total_usd":total_usd, 
        "stripe_publishable_key": settings.STRIPE_PUBLIC_KEY,
    }
    

    return render(request,"hotel/checkout.html",context)


@csrf_exempt
def create_checkout_session(request,booking_id):
    booking = Booking.objects.get(booking_id=booking_id)
    stripe.api_key = settings.STRIPE_SECRET_KEY

    checkout_session = stripe.checkout.Session.create(
        customer_email= booking.email,
        payment_method_types=['card'],
        line_items=[ 
            {
                'price_data':{
                    'currency':'USD', 
                    'product_data':{
                        'name':booking.fullname
                    }, 
                    'unit_amount':int(booking.total)
                }, 
                'quantity':1
            }
        ],
        mode= 'payment',
        success_url= request.build_absolute_uri(reverse('Hotel:success',args=[booking.booking_id]))+"?session_id{CHECKOUT_SESSION_ID}&succes_id="+booking.success_id+"&booking_total="+str(booking.total), 
        cancel_url= request.build_absolute_uri(reverse('Hotel:failed',args=[booking.booking_id]))
    )

    booking.payment_status = 'Processing'
    booking.stripe_payment_intent = checkout_session['id']
    booking.save()

    return JsonResponse({'sessionID':checkout_session.id})


def payment_success(request,booking_id):
    user=None
    if request.user.is_authenticated:
        print("Authenticated user: ", request.user)
        user = request.user


    success_id = request.GET.get('success_id')
    booking_total = request.GET.get('booking_total')
    if success_id and booking_total:
        success_id = success_id.rstrip("/")
        booking_total = booking_total.rstrip("/")

        booking = Booking.objects.get(booking_id=booking_id, success_id=success_id)
        if booking.total == Decimal(booking_total):
            if booking.payment_status == "Processing":
                booking.payment_status = 'Paid'
                booking.is_active = True
                booking.save()

                print("===========================================booking saved========================================")
                noti = Notifications.objects.create(
                    booking=booking, 
                    type="Booking Confirmed",
                    user=user
                )
                noti.save()
                print("===========================================Notification saved========================================")

                if 'selection_data_obj' in request.session:

templates/hotel/base.html
{% load static %}
{% comment %} {% load bootstrap5 %}

{% bootstrap_css %}
{% bootstrap_javascript %} {% endcomment %}
<!doctype html>
<html class="no-js" lang="zxx">

<head>
   <meta charset="utf-8">
   <meta http-equiv="x-ua-compatible" content="ie=edge">
   <title>Kalahari | {% block title %}{% endblock title %}</title>
   <meta name="description" content="">
   <meta name="viewport" content="width=device-width, initial-scale=1">

   <link rel="manifest" href="site.webmanifest">
   <link rel="shortcut icon" type="image/x-icon" href="{% static 'img/favicon.ico' %}">

   <!-- CSS here -->
   <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
   <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css'%}">
   <link rel="stylesheet" href="{% static 'css/gijgo.css'%}">
   <link rel="stylesheet" href="{% static 'css/slicknav.css'%}">
   <link rel="stylesheet" href="{% static 'css/animate.min.css'%}">
   <link rel="stylesheet" href="{% static 'css/magnific-popup.css'%}">
   <link rel="stylesheet" href="{% static 'css/fontawesome-all.min.css'%}">
   <link rel="stylesheet" href="{% static 'css/themify-icons.css'%}">
   <link rel="stylesheet" href="{% static 'css/slick.css'%}">
   <link rel="stylesheet" href="{% static 'css/nice-select.css'%}">
   <link rel="stylesheet" href="{% static 'css/style.css'%}">
   <link rel="stylesheet" href="{% static 'css/responsive.css'%}">
   <style>
      .rating {
    position: relative;
    display: flex;
    width: 2.875rem;
    height: 2.875rem;
    margin-top: -1.75rem;
    margin-left: 0.75rem;
    justify-content: center;
    align-items: center;
    border: .25rem solid #fff;
    border-radius: 50%;
    color: #fff;
    background-color: rebeccapurple
}
.star-rating {
    color: #f7b944;
}
   </style>
</head>

<body>

   <!-- Preloader Start -->
   <div id="preloader-active">
      <div class="preloader d-flex align-items-center justify-content-center">
         <div class="preloader-inner position-relative">
            <div class="preloader-circle"></div>
            <div class="preloader-img pere-text">
               <strong>{% block preloader %}{% endblock preloader %}</strong></b>
            </div>
         </div>
      </div>
   </div>
   <!-- Preloader Start -->

   <header>
      <!-- Header Start -->
      <div class="header-area header-sticky">
         <div class="main-header ">
            <div class="container">
               <div class="row align-items-center">
                  <!-- logo -->
                  <div class="col-xl-2 col-lg-2">
                     <div class="logo">
                        <a href="/"><img src="{% static 'img/kalahari_travels.png' %}" alt=""></a>
                     </div>
                  </div>
                  {% if request.user.is_authenticated %}
                  <div class="col-xl-8 col-lg-8">
                     <!-- main-menu -->
                     <div class="main-menu f-right d-none d-lg-block">
                        <nav>
                           <ul id="navigation">
                              <li><a href="{% url "Hotel:selected_rooms" %}">Rooms <span class="room-count"> {{request.session.selection_data_obj|length}}</span></a></li>
                              <li><a href="{% url "user_dashboard:dashboard" %}"> <i class="fa fa-tachometer" aria-hidden="true"></i><span class="room-count"> Dashboard</a></span></li>                            
                              
                           </ul> 
                        </nav>
                     </div>
                  </div>
                  <div class="col-xl-2 col-lg-2">  
                                        
                     <div class="header-btn">
                        <a href="{% url "user_dashboard:dashboard" %}" class="btn btn1 d-none d-lg-block "> <i class="fa fa-user-circle" aria-hidden="true"></i> {{request.user}}</a>
                     </div>
                  </div>
                  {% else %}
                  <div class="col-xl-8 col-lg-8">
                     <!-- main-menu -->
                     <div class="main-menu f-right d-none d-lg-block">
                        <nav>
                           <ul id="navigation">               
                              <li><a href="{% url "Hotel:selected_rooms" %}">Rooms <span class="room-count"> {{request.session.selection_data_obj|length}}</span></a></li>               
                              <li><a href="#">Account</a>
                                 <ul class="submenu">
                                    <li><a href="{% url "UserAuth:sign-in" %}">Sign In</a></li>
                                    <li><a href="{% url "UserAuth:sign-up" %}">Sign Up</a></li>
                                 </ul>
                              </li>
                              
                           </ul>
                        </nav>
                     </div>
                  </div>
                  <div class="col-xl-2 col-lg-2">                     
                     <div class="header-btn">
                        <a href="{% url "UserAuth:sign-in" %}" class="btn btn1 d-none d-lg-block "> <i class="fa fa-user-circle" aria-hidden="true"></i> Login</a>
                     </div>
                  </div>
                  
                  {% endif %}
                  <!-- Mobile Menu -->
                  <div class="col-12">
                     <div class="mobile_menu d-block d-lg-none"></div>
                  </div>
               </div>
            </div>
         </div>
      </div>
      <!-- Header End -->
   </header>
   <main>
      {% block content %}
      {% endblock content %}

   </main>


   <!-- JS here -->

   <!-- All JS Custom Plugins Link Here here -->
   <script src="{% static 'js/vendor/modernizr-3.5.0.min.js' %}"></script>

   <!-- Jquery, Popper, Bootstrap -->
   <script src="{% static 'js/vendor/jquery-1.12.4.min.js' %}"></script>
   <script src="{% static 'js/popper.min.js' %}"></script>
   <script src="{% static 'js/bootstrap.min.js' %}"></script>
   <!-- Jquery Mobile Menu -->
   <script src="{% static 'js/jquery.slicknav.min.js' %}"></script>

   <!-- Jquery Slick , Owl-Carousel Plugins -->
   <script src="{% static 'js/owl.carousel.min.js' %}"></script>
   <script src="{% static 'js/slick.min.js' %}"></script>
   <!-- Date Picker -->
   <script src="{% static 'js/gijgo.min.js' %}"></script>
   <!-- One Page, Animated-HeadLin -->
   <script src="{% static 'js/wow.min.js' %}"></script>
   <script src="{% static 'js/animated.headline.js' %}"></script>
   <script src="{% static 'js/jquery.magnific-popup.js' %}"></script>

   <!-- Scrollup, nice-select, sticky -->
   <script src="{% static 'js/jquery.scrollUp.min.js' %}"></script>
   <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
   <script src="{% static 'js/jquery.sticky.js' %}"></script>

   <!-- contact js -->
   <script src="{% static 'js/contact.js' %}"></script>
   <script src="{% static 'js/jquery.form.js' %}"></script>
   <script src="{% static 'js/jquery.validate.min.js' %}"></script>
   <script src="{% static 'js/mail-script.js' %}"></script>
   <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>

   <!-- Jquery Plugins, main Jquery -->
   <script src="{% static 'js/plugins.js' %}"></script>
   <script src="{% static 'js/main.js' %}"></script>
   <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
   <script>
      {% for message in messages %}
      Swal.fire({ 
         icon: '{{message.tags}}', 
         title: '{{message}}', 
         text: '{{message.tags}}',
         timer: 1500
      })
      {% endfor %}
   </script>


</body>

</html>

templates/hotel/footer.html
{% load static %}
<footer>
   <!-- Footer Start-->
   <div class="footer-area black-bg footer-padding">
      <div class="container">
         <div class="row d-flex justify-content-between">
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6">
               <div class="single-footer-caption mb-30">
                  <!-- logo -->
                  <div class="footer-logo">
                     <a href="/"><img src="{% static 'img/logo/logo2_footer.png'%}" alt=""></a>
                  </div>
                  <div class="footer-social footer-social2">
                     <a href="#"><i class="fab fa-facebook-f"></i></a>
                     <a href="#"><i class="fab fa-twitter"></i></a>
                     <a href="#"><i class="fas fa-globe"></i></a>
                     <a href="#"><i class="fab fa-behance"></i></a>
                  </div>
                  <div class="footer-pera">
                     <p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        Copyright ©<script>
                           document.write(new Date().getFullYear());
                        </script> All rights reserved | This template is made with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                     </p>
                  </div>
               </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-3 col-sm-5">
               <div class="single-footer-caption mb-30">
                  <div class="footer-tittle">
                     <h4>Quick Links</h4>
                     <ul>
                        <li><a href="#">About Mariana</a></li>
                        <li><a href="#">Our Best Rooms</a></li>
                        <li><a href="#">Our Photo Gellary</a></li>
                        <li><a href="#">Pool Service</a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-3 col-sm-3">
               <div class="single-footer-caption mb-30">
                  <div class="footer-tittle">
                     <h4>Reservations</h4>
                     <ul>
                        <li><a href="#">Tel: 345 5667 889</a></li>
                        <li><a href="#">Skype: Marianabooking</a></li>
                        <li><a href="#">reservations@hotelriver.com</a></li>
                     </ul>
                  </div>
               </div>
            </div>
            <div class="col-xl-3 col-lg-3 col-md-4  col-sm-5">
               <div class="single-footer-caption mb-30">
                  <div class="footer-tittle">
                     <h4>Our Location</h4>
                     <ul>
                        <li><a href="#">198 West 21th Street,</a></li>
                        <li><a href="#">Suite 721 New York NY 10016</a></li>
                     </ul>
                     <!-- Form -->
                     <div class="footer-form">
                        <div id="mc_embed_signup">
                           <form target="_blank" action="#" method="get" class="subscribe_form relative mail_part">
                              <input type="email" name="email" id="newsletter-form-email" placeholder="Email Address" class="placeholder hide-on-focus" onfocus="this.placeholder = ''" onblur="this.placeholder = ' Email Address '">
                              <div class="form-icon">
                                 <button type="submit" name="submit" id="newsletter-submit" class="email_icon newsletter-submit button-contactForm"><img src="{% static "img/logo/form-iocn.jpg" %}" alt=""></button>
                              </div>
                              <div class="mt-10 info"></div>
                           </form>
                        </div>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   <!-- Footer End-->
</footer>

templates/hotel/hotel_listing.html
{% load static %}
<!-- Blog Start -->
<div class="blog-area blog-padding">
    <div class="container">
        
        <div class="row">
            {% for hotel in hotels %}
            {% comment %} <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="{{hotel.image.url}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{hotel.name}}</h5>
                <p class="card-text">{{hotel.mobile}}.</p>
                <a href="{% url "Hotel:hotel_detail" hotel.slug %}" class="btn btn-primary">View</a>
            </div> {% endcomment %}
            <div class="col-lg-6">
                <!-- Single Blog --> 
                <div class="single-blog mb-30">
                    <div class="blog-img">
                        <a href="{% url "Hotel:hotel_detail" hotel.slug %}"><img src="{{hotel.image.url}}" height="300" width="300" alt=""></a>
                    </div>
                    <div class="blog-caption">
                        <div class="blog-cap-top d-flex justify-content-between mb-40">
                            <ul>
                                <li><span class="fa fas-phone"></span><a href="{% url "Hotel:hotel_detail" hotel.slug %}"> {{hotel.mobile}}</a></li>
                                <li><spanclass="fas fa-phone"></span><a href="{% url "Hotel:hotel_detail" hotel.slug %}"> {{hotel.email}}</a></li>
                                
                            </ul>
                        </div>
                        <div class="blog-cap-mid">
                            <p><a href="{% url "Hotel:hotel_detail" hotel.slug %}">{{hotel.name}}</a></p>
                        </div>
                        <!-- Comments -->
                        <div class="blog-cap-bottom d-flex justify-content-between">
                            <span>{{hotel.email}}</span>
                            <span><img src="{% static 'img/our_blog/blog-comments-icon.jpg'%}" alt="">3</span>
                        </div>
                    </div>
                </div>
            </div>
            {%endfor%}
        </div>
    </div>
 </div>
 <!-- Blog End -->

templates/hotel/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Navbar brand -->
    <div class="nav-item">
      
      <a class="navbar-brand" href="/">Kalahari Travel</a>
    </div>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
      aria-label="Toggle navigation">
      <i class="fas fa-bars text-light"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Left links -->
      <ul class="navbar-nav me-auto d-flex flex-row mt-3 mt-lg-0">
        <li class="nav-item text-center mx-2 mx-lg-1 ">
          <a class="nav-link active" href="#!">
            <span>
              <i class="far fa-envelope fa-lg mb-1"></i>
            </span>
            About us
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1 ">
          <a class="nav-link active" href="#!">
            <span>
              <i class="far fa-envelope fa-lg mb-1"></i>
            </span>
            Contact
          </a>
        </li>
        {% if request.user.is_authenticated %}
        <li class="nav-item text-center mx-2 mx-lg-1 ">
          <a class="nav-link active" href="#">
            <span>
              <i class="far fa-dashboard fa-lg mb-1"></i>
            </span>
            Dashboard
          </a>
        </li>
        {% endif %}
        {% comment %} 
        <li class="nav-item dropdown text-center mx-2 mx-lg-1">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown"
            aria-expanded="false">
            <div>
              <i class="far fa-envelope fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-primary">11</span>
            </div>
            Dropdown
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="#">Something else here</a>
            </li>
          </ul>
        </li> 
        {% endcomment %}
      </ul>
      <!-- Left links -->
      <!-- Search form -->
      <form class="d-flex input-group w-auto ms-lg-3 my-3 my-lg-0">
        <input type="search" class="form-control" placeholder="Search" aria-label="Search" />
        <button class="btn btn-primary" type="button" data-mdb-ripple-color="dark">
          Search
        </button>
      </form>
      <!-- Right links -->
      {% if request.user.is_authenticated %}
      <ul class="navbar-nav ms-auto d-flex flex-row mt-3 mt-lg-0 "style="margin-right:100px;">
        <li class="nav-item dropdown text-center mx-2 mx-lg-1" style="margin-right:100px;">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            {{request.user.username}}
          </a>
          <!-- Dropdown menu -->
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Change Password</a></li>
            <li><a class="dropdown-item" href="#">Reset Password</a></li>
            <li>
              <hr class="dropdown-divider" />
            </li>
            <li>
              <a class="dropdown-item" href="{% url "UserAuth:logout" %}">Logout</a>
            </li>
          </ul>
        </li> 
        
      </ul>
      {% else %}
      <ul class="navbar-nav ms-auto d-flex flex-row mt-3 mt-lg-0 ">

        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link active" href="{% url "UserAuth:sign-in" %}">
            {% comment %} <div>
              <i class="fas fa-bell fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-info">11</span>
            </div> {% endcomment %}
            Login
          </a>
        </li>
        <li class="nav-item text-center mx-2 mx-lg-1">
          <a class="nav-link active" href="{% url "UserAuth:sign-up" %}">
            {% comment %} <div>
              <i class="fas fa-globe-americas fa-lg mb-1"></i>
              <span class="badge rounded-pill badge-notification bg-success">11</span>
            </div> {% endcomment %}
            Register
          </a>
        </li>
      </ul>
      {% endif %}
      
    <!-- Right links -->
      
        

      
     
      
    </div>
    <!-- Collapsible wrapper -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->