Hotel/urls.py
from django.urls import path

from .views import *

app_name= 'Hotel'

urlpatterns = [
    path("",home,name='home'),
    path("hotel/<slug>",hotel_detail,name='hotel_detail'),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>",room_type_detail,name="room_type_detail"),
    path("selected_rooms/",selected_rooms,name="selected_rooms"),
    path("checkout/<booking_id>/",checkout,name="checkout"),
    path("update_room_status/",update_room_status,name="update_room_status"),
    



    #payments routes 
    path("api/create_checkout_session/<booking_id>/",create_checkout_session,name='api_checkout_session'),
    path('success/<booking_id>/',payment_success, name='success'),
    path('failed/<booking_id>/',payment_failed, name='failed'),
]

UserAuth/urls.py
from django.urls import path

from .views import *

app_name= 'UserAuth'

urlpatterns = [
    path("sign-up",registerView,name='sign-up'),
    path("sign-in",loginViewTemp,name='sign-in'),
    path("logout",logoutView,name='logout'),
]

travel_booking_platform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Hotel import views as hotel_views
from django.conf import settings


from django.conf.urls.static import static


urlpatterns = [ 
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin/', admin.site.urls),
    path("",hotel_views.home,name="home"),

    # custom urls
    # userauth urls
    path('user/',include("UserAuth.urls")),

    # hotel ursl
    path('',include("Hotel.urls")),

    # booking ursl
    path('booking/',include("booking.urls")),

    # booking ursl
    path('dashboard/',include("User_dashboard.urls")),


    # ckeditor ursl
    path('ckeditor5/',include("django_ckeditor_5.urls")),


    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

UserAuth/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser


# from shortuuid.dango_fields import shortUUIDField

# Create your models here.
GENDER = (
    ('Male',"Male"),
    ('Female',"Female"),
)
IDENTITY_TYPE = (
    ("National Identity Card Number","National Identity Card Number"),
    ("Driver's License","Driver's License"),
    ("Passport Number","Passport Number"),
) 


def user_directory_path(instance,filename):
    ext = filename.split(".")[-1]
    filename = "%s.%s" % (instance.user.id,filename)
    return "user_{0}/{1}".format(instance.user.id,filename)

class User(AbstractUser):
    full_name = models.CharField(max_length=225,null=True,blank=True)
    username = models.CharField(max_length=225, unique=True)
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=255,null=True, blank=True)
    gender = models.CharField(max_length=255,choices=GENDER,default='male')

    otp = models.CharField(max_length=20,null=True, blank=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    


class Profile(models.Model):
    # pid = models.UUIDField(length=7, max_length=15,alphabets="abcdefghijklmnopqrstuvwxyz12345",unique=True)
    image = models.FileField(upload_to=user_directory_path,default='default.jpg',blank=True, null=True)
    user = models.OneToOneField(User, blank=True,on_delete=models.CASCADE)
    full_name = models.CharField(max_length=225,null=True,blank=True)
    phone = models.CharField(max_length=255,null=True, blank=True)
    gender = models.CharField(max_length=255,choices=GENDER,default='male')
    
    country = models.CharField(max_length=255,null=True, blank=True)
    identity_type = models.CharField(max_length=255,choices=IDENTITY_TYPE,null=True, blank=True)
    id_image = models.FileField(upload_to=user_directory_path,default='default.jpg',blank=True, null=True)

    
    Facebook = models.URLField(null=True, blank=True)
    Twitter = models.URLField(null=True, blank=True)
    Instagram = models.URLField(null=True, blank=True)

    wallet = models.DecimalField(max_digits=12, decimal_places=2,default=0.00)
    verified = models.BooleanField(default=False)
    date = models.DateField(auto_now_add=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        if self.full_name:
            return self.full_name
        else:
            return self.user.username
        



# to create a user profile once user is created
def create_user_profile(sender,instance,created,**kwargs):
    if created:
        Profile.objects.create(user=instance)


# to save the creted user profile
def save_user_profile(sender,instance,**kwargs):
    instance.profile.save()


post_save.connect(create_user_profile, sender=User)
post_save.connect(save_user_profile, sender=User)

UserAuth/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from .models import User, Profile

class UserRegisterForm(UserCreationForm):
    full_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "full name"}))
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "username"}))
    email = forms.EmailField(widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "email"}))
    phone = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control', "placeholder": "phone number"}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "password"}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control', "placeholder": "confirm Password"}))
    class Meta:
        model = User
        fields = ['full_name','username','email','phone','password1','password2']

UserAuth/views.py
from django.shortcuts import render,redirect
from django.contrib.auth import authenticate,login,logout
from django.contrib import messages

from .models import User,Profile
from .forms import UserRegisterForm
# Create your views here.
def registerView(request):
    form = UserRegisterForm(request.POST or None)
    if form.is_valid():
        form.save()
        full_name = form.cleaned_data['full_name']
        phone = form.cleaned_data['phone']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password1']


        # to login the new user created
        user = authenticate(email=email, password=password)
        login(request,user)
        messages.success(request, f"Hey {full_name}, your account has been created successfully")

        # to create a profile for the new user
        profile = Profile.objects.get(user=request.user)
        profile.full_name = full_name
        profile.phone = phone
        profile.save()

        return redirect('Hotel:home')
    context = {
        'form': form,
    }
    return render(request, 'userauths/sign-up.html', context)


def loginViewTemp(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        password = request.POST.get('password')

        try:
            user_query = User.objects.get(email=email)
            user_auth = authenticate(request, email=email, password=password)
            if user_query:
                login(request,user_auth)
                messages.success(request,"login successful")
                #  to redirect the user to the page they were b4 login successful
                next_url = request.GET.get('next',"Hotel:home")
                return redirect(next_url)  
            else:
                messages.error(request,"invalid login")
        except:
            messages.error(request,"No account found for this email address")
            return redirect("UserAuth:sign-in")
            

    return render(request, 'userauths/sign-in.html',)
    

def logoutView(request):
    logout(request)
    messages.success(request, "You have been logged out")
    return redirect("UserAuth:sign-in")

templates/userauths/sign-in.html
{% extends "hotel/base.html" %}
{% block title %}Sign In{% endblock title %}
{% load static %}
{% block content %}
{% block preloader %}Login{% endblock preloader %}
<section class="vh-100 home-banner-area">

   <div class="container py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
         <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
               <div class="row g-0">
                  <div class="col-sm-6 d-flex d-md-block">
                     <img src="{% static "img/hero/h1_hero.jpg"%}" height="450" width="450" alt="login form" class="img-fluidr" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-sm-6 d-flex align-items-center">
                     <div class="card-body  ps-5 text-black">
                        <h5 class="fw-normal mb-3 pb-2 text-center" style="letter-spacing: 1px;">SignIn your account</h5>

                        <form action="" method='post'>
                           {% csrf_token %}


                           {% if form.errors %}
                              <p class="small text-danger">Invalid username or password</p>
                           {% endif %}
                           <div class="form-outline mb-4">
                              <input type="email" class="form-control form-control-lg" name="email" autofocus autocapitalize="none" autocomplete="email" maxlength="150" required id="id_email" placeholder="email" />

                           </div>

                           <div class="form-outline mb-2">
                              <input type="password" class="form-control form-control-lg" name="password" autocomplete="current-password" required id="id_password" placeholder="password" />

                           </div>
                           <div class="row g-0">
                              <div class="pt-1 mb-2 col">
                                 <input class="btn btn-success btn-lg btn-block w-75" type="submit" value='Login' />
                              </div>
                              <div class="pt-1 mb-2 col">

                                 <a class="small text-muted3" style="color: #e62d92;" href="#" data-bs-toggle="modal" data-bs-target="#exampleModal">Forgot password?</a>
                              </div>
                              <p class="mb-0 pb-lg-2" style="color: #393f81;">Don't have an account?
                                 <a href="{% url "UserAuth:sign-up" %}" style="color: #14ee88;">Register here</a>
                              </p>
                           </div>
                        </form>

                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
</section>

{% endblock content %}

templates/userauths/sign-up.html
{% extends "hotel/base.html" %}
{% load static %}
{% block title %}Sign Up{% endblock title %}
{% block preloader %}Register{% endblock preloader %}
{% block content %}
<section class="vh-100 home-banner-area">
   <div class="container py-3 h-100">
      <div class="row d-flex justify-content-center align-items-center h-100">
         <div class="col col-xl-10">
            <div class="card" style="border-radius: 1rem;">
               <div class="row g-0">
                  <div class="col-sm-6 d-flex d-md-block">
                     <img src="{% static "img/hero/h1_hero.jpg"%}" height="450" width="450" alt="login form" class="img-fluidr" style="border-radius: 1rem 0 0 1rem;" />
                  </div>
                  <div class="col-sm-6 d-flex align-items-center">
                     <div class="card-body  ps-5 text-black">
                        <h5 class="fw-normal mb-3 pb-2 text-center" style="letter-spacing: 1px;">Register your account</h5>

                        <form method="post" action="">
                           {% csrf_token %}

                           <div class="form-outline mb-2 row d-fluid">
                              {{form.full_name}}

                           </div>

                           <div class="form-outline mb-2 row d-fluid">
                              {{form.email}}
                              {% if form.email.errors %}
                              <ul class="small">
                                 {% for error in form.email.errors %}
                                 <li class="small text-danger">{{ error }}</li>
                                 {% endfor %}
                              </ul>
                              {% endif %}

                           </div>
                           <div class="form-outline mb-2 row d-fluid">
                              {{form.username}}
                              {% if field.username.errors %}
                              <ul class="small">
                                 {% for error in form.username.errors %}
                                 <li class="small text-danger">{{ error }}</li>
                                 {% endfor %}
                              </ul>
                              {% endif %}
                           </div>
                           <div class="form-outline mb-2 row d-fluid">
                              {{form.phone}}

                           </div>

                           <div class="form-outline mb-2 row d-fluid">
                              {{form.password1}}
                              {% if form.password1.errors %}
                              <ul class="small">
                                 {% for error in form.password1.errors %}
                                 <li class="small text-danger">{{ error }}</li>
                                 {% endfor %}
                              </ul>
                              {% endif %}

                           </div>
                           <div class="form-outline mb-2 row d-fluid">
                              {{form.password2}}
                              {% if form.password2.errors %}
                              <ul class="small">
                                 {% for error in form.password2.errors %}
                                 <li class="small text-danger">{{ error }}</li>
                                 {% endfor %}
                              </ul>
                              {% endif %}
                           </div>


                           <div class="row g-0">
                              <div class="pt-1 mb-0 col">
                                 <button class="btn btn-primary btn-lg btn-block w-100" type="submit">SignUp</button>
                              </div>
                              <div class="pt-1 mb-2 col">
                                 <p class="mb-2 pb-lg-2" style="color: #393f81;">Have an account? <a href="{% url "UserAuth:sign-in" %}" style="color: #14ee88;">Login here</a></p>
                              </div>
                           </div>
                        </form>
                     </div>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
   {% endblock content %}