Hotel/urls.py
from django.urls import path

from .views import *

app_name= 'Hotel'

urlpatterns = [
    path("",home,name='home'),
    path("hotel/<slug>",hotel_detail,name='hotel_detail'),
    path("detail/<slug:slug>/room-type/<slug:rt_slug>",room_type_detail,name="room_type_detail"),
    path("selected_rooms/",selected_rooms,name="selected_rooms"),
    path("checkout/<booking_id>/",checkout,name="checkout"),
    path("update_room_status/",update_room_status,name="update_room_status"),
    



    #payments routes 
    path("api/create_checkout_session/<booking_id>/",create_checkout_session,name='api_checkout_session'),
    path('success/<booking_id>/',payment_success, name='success'),
    path('failed/<booking_id>/',payment_failed, name='failed'),
]

UserAuth/urls.py
from django.urls import path

from .views import *

app_name= 'UserAuth'

urlpatterns = [
    path("sign-up",registerView,name='sign-up'),
    path("sign-in",loginViewTemp,name='sign-in'),
    path("logout",logoutView,name='logout'),
]

User_dashboard/urls.py
from django.urls import path 
from .views import *

app_name="user_dashboard"

urlpatterns = [
    path("",dasboard,name="dashboard"),
    path("bookings/",bookings,name="bookings"),
    path("notifications/",notifications ,name="notifications"),
    path("mark_as_read/<id>/",mark_as_read ,name="mark_as_read"),
    path("booking_details/<booking_id>",booking_details,name="booking_details")
]

booking/urls.py
from django.urls import path 

from .views import *  
app_name="booking" 

urlpatterns =[ 
    path("check_room_availabilty", check_room_availabilty, name="check_room_availabilty"),
    path("add_to_selection/", add_to_selection, name="add_to_selection"),
    path("delete_selection/", delete_selection, name="delete_selection"),
]

travel_booking_platform/urls.py
from django.contrib import admin
from django.urls import path,include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from Hotel import views as hotel_views
from django.conf import settings


from django.conf.urls.static import static


urlpatterns = [ 
    path('admin_tools_stats/', include('admin_tools_stats.urls')),
    path('admin/', admin.site.urls),
    path("",hotel_views.home,name="home"),

    # custom urls
    # userauth urls
    path('user/',include("UserAuth.urls")),

    # hotel ursl
    path('',include("Hotel.urls")),

    # booking ursl
    path('booking/',include("booking.urls")),

    # booking ursl
    path('dashboard/',include("User_dashboard.urls")),


    # ckeditor ursl
    path('ckeditor5/',include("django_ckeditor_5.urls")),


    
]

urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

User_dashboard/models.py
from django.db import models

# Create your models here.

booking/models.py
from django.db import models

# Create your models here.

User_dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.db import models
from django.contrib import messages
from Hotel.models import *

# Create your views here.

@login_required
def dasboard(request):
    booking = Booking.objects.filter(user=request.user,payment_status="Paid")
    total_spent = Booking.objects.filter(user=request.user,payment_status="Paid").aggregate(amount=models.Sum('total'))

    context = {
        "bookings":booking,
        "total_spent":total_spent
    }

    return render(request,"user_dashboard/dashboard.html",context)


@login_required 
def bookings(request):
    bookings = Booking.objects.filter(user=request.user,payment_status="Paid")
    context = {
        'bookings':bookings
    }
    return render(request,"user_dashboard/bookings.html",context) 


@login_required 
def booking_details(request,booking_id):
    booking = Booking.objects.get(booking_id=booking_id,user=request.user,payment_status="Paid")
    context = {
        'booking':booking 
    }
    return render(request,"user_dashboard/booking_details.html",context)
    

@login_required 
def notifications(request):
    notifications = Notifications.objects.filter(user= request.user,seen=False)

    context = {
        'notifications':notifications 
    }
    return render(request,"user_dashboard/notifications.html",context)


@login_required
def mark_as_read(request,id):
    noti = Notifications.objects.get(id=id)
    noti.seen = True 
    noti.save() 
    messages.success(request, "Notification marked as read!")

    return redirect("user_dashboard:notifications")

booking/views.py
from datetime import datetime as dt
from django.shortcuts import render,redirect
from django.urls import reverse
from django.http import HttpResponseRedirect, JsonResponse
from Hotel.models import *
from django.template.loader import render_to_string
from django.contrib import messages

# Create your views here.

def check_room_availabilty(request): 
    if request.method == "POST": 
        id = request.POST.get("hotel-id")
        checkin = request.POST.get("checkin")
        checkout = request.POST.get("checkout")
        adults = request.POST.get("adults")
        children = request.POST.get("children")
        roomtype = request.POST.get("room_type")
        

        hotel = Hotel.objects.get(id=id)
        room_type = RoomType.objects.get(hotel=hotel,slug=roomtype)
        
       
        url = reverse("Hotel:room_type_detail", args=[hotel.slug, room_type.slug])
        url_with_params = f"{url}?hotel-id={id}&checkin={checkin}&checkout={checkout}&adults={adults}&children={children}&room_type={room_type}"
        return HttpResponseRedirect(url_with_params)
    

def add_to_selection(request): 
    room_selection={} 
    room_selection[str(request.GET["id"])]={ 
        'hotel_id':request.GET['hotel_id'],
        'hotel_name':request.GET['hotel_name'],
        'room_id':request.GET['room_id'],
        'room_type':request.GET['room_type'],
        'room_name':request.GET['room_name'],
        'room_price':request.GET['room_price'],
        'number_of_beds':request.GET['number_of_beds'],
        'room_number':request.GET['room_number'],
        'checkin':request.GET['checkin'],
        'checkout':request.GET['checkout'],
        'adults':request.GET['adults'],
        'children':request.GET['children'],
    }
    if "selection_data_obj" in request.session:
        if str(request.GET["id"]) in request.session['selection_data_obj']:
            selection_data = request.session['selection_data_obj']
            selection_data[str(request.GET['id'])]['adults'] = int(room_selection[str(request.GET["id"])]["adults"]) 
            selection_data[str(request.GET['id'])]['children'] = int(room_selection[str(request.GET["id"])]["children"]) 
            request.session['selection_data_obj']=selection_data
        else: 
            selection_data = request.session['selection_data_obj']
            selection_data.update(room_selection)
            request.session['selection_data_obj']=selection_data 
    else:
        request.session['selection_data_obj']=room_selection

    data = { 
        "data":request.session['selection_data_obj'], 
        "name":"lijan",
        "total_selected_item":len(request.session['selection_data_obj'])
    }
    messages.success(request, "Added to cart")
    return JsonResponse(data)


def delete_selection(request):
    hotel_id = str(request.GET['id'])
    if "selection_data_obj" in request.session:
        if hotel_id in request.session['selection_data_obj']:
            selection_data = request.session['selection_data_obj']
            del request.session['selection_data_obj'][hotel_id]
            request.session['selection_data_obj'] = selection_data

    total=0
    room_count=0
    total_days=0
    adults=0
    children=0
    checkin=""
    checkout=""
    hotel=None

    if 'selection_data_obj' in request.session:
        for h_id,items in request.session['selection_data_obj'].items():
            id= int(items['hotel_id'])
            checkin= items['checkin']
            checkout= items['checkout']
            adults= int(items['adults']) 
            children= int(items['children']) 
            room_type_= int(items['room_type'])
            room_id= int(items['room_id'])


            room_type = RoomType.objects.get(id=room_type_)

            date_format = "%Y-%m-%d"
            checkin_date = dt.strptime(checkin, date_format)
            checkout_date = dt.strptime(checkout, date_format)
            time_difference = checkout_date - checkin_date

            total_days = time_difference.days
            room_count +=1
            days = total_days
            price = room_type.price
            
            room_price = price*room_count 
            total = room_price*days
            

    context = render_to_string(
        'hotel/async/selected_room.html',
        {
            "data":request.session['selection_data_obj'],
            "total_selected_item":len(request.session['selection_data_obj']),
            "total":total, 
            "total_days":total_days, 
            "adults":adults, 
            "chilren":children,
            "checkin":checkin,
            "checkout":checkout,
            "hotel":hotel,
        }
    )
    # print("=======================================================\n=======================",context)
    return JsonResponse({"data":context, "total_selected_item":len(request.session['selection_data_obj']),}) 

templates/user_dashboard/booking_details.html
{% extends "user_dashboard/base.html" %}
{% load static %}
{% block title %} Booking Details{% endblock title %}
{% block body %}
<!-- Content Row -->
<div class="row">

    <div class="col-xl-8 col-lg-7">

        <!-- Area Chart -->
        <div class="card shadow mb-4">
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Booking ID: {{booking.booking_id}}</h6>
            </div>
            <div class="card-body">
                <h3>{{booking.fullname | title}} 
                    <span class="badge badge-success text-small"><small>{{booking.payment_status}}</small></span>
                </h3>
                <p>Hotel Name: <span class="text-dark">{{booking.hotel.name | title  }}</span></p>
                <p>Hotel Address: <span class="text-dark">{{booking.hotel.address }}</span></p>
                <p>Hotel Email: <span class="text-dark">{{booking.hotel.email}}</span></p>
                <p>Hotel Phone: <span class="text-dark">{{booking.hotel.mobile }}</span></p>
                <hr>
                <p>Checkin Date: <span class="text-dark">{{booking.checkin_date }}</span></p>
                <p>checkout Date: <span class="text-dark">{{booking.checkout_date }}</span></p>
                <p>Total Days: <span class="text-dark">{{booking.total_days }} Days</span></p>
                <p>Adults: <span class="text-dark">{{booking.num_adults }} adults</span></p>
                <p>Children: <span class="text-dark">{{booking.num_children }} children</span></p>
                <hr>
                <p>Full Name: <span class="text-dark">{{booking.fullname }}</span></p>
                <p>Email: <span class="text-dark">{{booking.email}}</span></p>
                <p>Phone Number: <span class="text-dark">{{booking.phone }}</span></p>
                <hr>
                <p>Total: <span class="text-dark">{{booking.total }}</span></p>
                <hr>
                <p>Booking Date: <span class="text-dark">{{booking.booking_date}}</span></p>
            </div>
        </div>

        

    </div>

    <!-- Donut Chart -->
    <div class="col-xl-4 col-lg-5">
        <div class="card shadow mb-4">
            <!-- Card Header - Dropdown -->
            <div class="card-header py-3">
                <h6 class="m-0 font-weight-bold text-primary">Booked Rooms ({{booking.room.all.count}}) </h6>
            </div>
            <!-- Card Body -->
            {% for r in booking.room.all %}
            <div class="card-body">
                <h6>Room Type: {{r.room_type.type | title}}</h6>
                <p>Room Number: {{r.room_number }}</p>
                <p>Room price: {{r.room_type.price }}</p>
                <hr>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock body %}

templates/user_dashboard/bookings.html
{% extends "user_dashboard/base.html" %}
{% load static %}
{% block title %}Bookings{% endblock title %}
{% block body %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">All bookings</h1>
       <!-- DataTales Example -->
    {% for booking in bookings %}
    <div class="card shadow mb-4 ">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            <h6 class="m-0 font-weight-bold text-primary">Booking ID: {{ booking.booking_id }}</h6>
            <a href="{% url "user_dashboard:booking_details" booking.booking_id %}" class="btn btn-info ml-auto">
                <i class="fas fa-fw fa-eye"></i>View
            </a>
        </div>
        
        <div class="card-body ">
            <h3>{{booking.fullname | title}} 
                <span class="badge badge-success text-small"><small>{{booking.payment_status}}</small></span>
            </h3>
            <p class="fs-6">Hotel Name: <span class="text-dark">{{booking.hotel.name | title  }}</span></p>
            
            <p>Checkin Date: <span class="text-dark">{{booking.checkin_date }}</span></p>
            <p>checkout Date: <span class="text-dark">{{booking.checkout_date }}</span></p>
                
            <p>Total: <span class="text-dark">Kshs.{{booking.total }}</span></p>
           
        </div>
    </div> 
    {% endfor %}

</div>

{% endblock body %}

templates/user_dashboard/dashboard.html
{% extends "user_dashboard/base.html" %}
{% load static %}

{% block body %}
<!-- Page Heading -->
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800">Summaries</h1>
</div>

<!-- Content Row -->
{% include "user_dashboard/toprow.html" %}
<table class="table table-striped table-hover table-responsive-sm">
  <thead class="thead-dark">
    <tr>
      <th scope="col">S/N</th>
      <th scope="col">Hotel Name</th>
      <th scope="col">Total Rooms</th>
      <th scope="col">Booking Date</th>
      <th scope="col">Payment Status</th>
      <th scope="col">View Booking</th>
    </tr>
  </thead>
  <tbody>
    {% for booking in bookings %}
      <tr>
          <th scope="row">{{forloop.counter}}</th>
          <td>{{booking.hotel}}</td>
          <td>{{booking.room.all.count}}</td>
          <td>{{booking.booking_date}}</td>
          <td><span class="badge badge-success">{{booking.payment_status}}</span></td>
          <td><a href="{% url "user_dashboard:booking_details" booking.booking_id %}" class="btn btn-info"><i class="fas fa-fw fa-eye"></i>View</a></td>
      </tr>
    {% endfor %}
   
  </tbody>
</table>
{% endblock body %} 

templates/user_dashboard/notifications.html
{% extends "user_dashboard/base.html" %}
{% load static %}
{% block title %}Notifications{% endblock title %}
{% block body %}
<!-- Begin Page Content -->
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Notifications</h1>
       <!-- DataTales Example -->
    {% for notification in notifications %}
    <div class="card shadow mb-4 ">
        <div class="card-header py-3 d-flex justify-content-between align-items-center">
            {% if notification.type == "Booking Confirmed" %}
            <h6 class="m-0 font-weight-bold text-success">Your booking of ID: #<code>{{notification.booking.booking_id}}</code> has been placed successfuly!</h6>
            <a href="{% url "user_dashboard:mark_as_read" notification.id %}" class="btn ">
                <i class="fas fa-fw fa-times" aria-hidden="true"></i>
            </a>
            {% else %}
            <h6 class="m-0 font-weight-bold text-warning">Your booking of ID: #<code>{{notification.booking.booking_id}}</code> has been cancelled successfuly!</h6>
            <a href="{% url "user_dashboard:mark_as_read" notification.id %}" class="btn ">
                <i class="fas fa-fw fa-times" aria-hidden="true"></i>
            </a>
            {% endif %}
        </div>       
        
    </div> 
    {% endfor %}

</div>

{% endblock body %}

templates/user_dashboard/sidebar.html
{% load static %}
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

    <!-- Sidebar - Brand -->
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="#">
        <div class="sidebar-brand-icon rotate-n-15">
            <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">{{request.user}}</div>
    </a>

    <!-- Divider -->
    <hr class="sidebar-divider my-0">

    <!-- Nav Item - Dashboard -->
    <li class="nav-item active">
        <a class="nav-link" href="{% url "user_dashboard:dashboard" %}">
            <i class="fas fa-fw fa-tachometer-alt"></i>
            <span>Dashboard</span></a>
    </li>
    
    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Interface
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
            aria-expanded="true" aria-controls="collapseTwo">
            <i class="fa fa-calendar" aria-hidden="true"></i>
            <span>Bookings</span>
        </a>
        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Your bookings:</h6>
                <a class="collapse-item" href="{% url "user_dashboard:bookings" %}">All Bookings</a>
                {% comment %} <a class="collapse-item" href="cards.html">Cards</a> {% endcomment %}
            </div>
        </div>
    </li>

    <!-- Nav Item - Utilities Collapse Menu -->
    <li class="nav-item">
        <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
            aria-expanded="true" aria-controls="collapseUtilities">
            <i class="fas fa-fw fa-wrench"></i>
            <span>Account</span>
        </a>
        <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
            data-parent="#accordionSidebar">
            <div class="bg-white py-2 collapse-inner rounded">
                <h6 class="collapse-header">Account Utilities:</h6>
                <a class="collapse-item" href="">Profile</a>
                <a class="collapse-item" href="">Change Password</a>
                <a class="collapse-item" href="">Logout</a>
            </div>
        </div>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider">

    <!-- Heading -->
    <div class="sidebar-heading">
        Addons
    </div>

    <!-- Nav Item - Pages Collapse Menu -->
    

    <!-- Nav Item - Charts -->
    <li class="nav-item">
        <a class="nav-link" href="{% url "user_dashboard:notifications" %}">
            <i class="fas fa-fw fa-bell"></i>
            <span>Notifications</span></a>
    </li>

    <!-- Nav Item - Tables -->
    <li class="nav-item">
        <a class="nav-link" href="">
            <i class="fas fa-fw fa-wallet"></i>
            <span>Wallet</span></a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="">
            <i class="fas fa-fw fa-bookmark"></i>
            <span>Bookmarks</span></a>
    </li>

    <!-- Divider -->
    <hr class="sidebar-divider d-none d-md-block">

    <!-- Sidebar Toggler (Sidebar) -->
    <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
    </div>

   

</ul>
<!-- End of Sidebar -->

templates/user_dashboard/topbar.html
{% load static %}
<!-- Topbar -->
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

    <!-- Sidebar Toggle (Topbar) -->
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>

    <!-- Topbar Search -->
    <form
        class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..."
                aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">

        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
        <li class="nav-item dropdown no-arrow d-sm-none">
            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                aria-labelledby="searchDropdown">
                <form class="form-inline mr-auto w-100 navbar-search">
                    <div class="input-group">
                        <input type="text" class="form-control bg-light border-0 small"
                            placeholder="Search for..." aria-label="Search"
                            aria-describedby="basic-addon2">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="button">
                                <i class="fas fa-search fa-sm"></i>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </li>

        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-bell fa-fw"></i>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">3+</span>
            </a>
            <!-- Dropdown - Alerts -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="alertsDropdown">
                <h6 class="dropdown-header">
                    Alerts Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-primary">
                            <i class="fas fa-file-alt text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 12, 2019</div>
                        <span class="font-weight-bold">A new monthly report is ready to download!</span>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-success">
                            <i class="fas fa-donate text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 7, 2019</div>
                        $290.29 has been deposited into your account!
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="mr-3">
                        <div class="icon-circle bg-warning">
                            <i class="fas fa-exclamation-triangle text-white"></i>
                        </div>
                    </div>
                    <div>
                        <div class="small text-gray-500">December 2, 2019</div>
                        Spending Alert: We've noticed unusually high spending for your account.
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
            </div>
        </li>

        <!-- Nav Item - Messages -->
        <li class="nav-item dropdown no-arrow mx-1">
            <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-envelope fa-fw"></i>
                <!-- Counter - Messages -->
                <span class="badge badge-danger badge-counter">7</span>
            </a>
            <!-- Dropdown - Messages -->
            <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="messagesDropdown">
                <h6 class="dropdown-header">
                    Message Center
                </h6>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_1.svg"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div class="font-weight-bold">
                        <div class="text-truncate">Hi there! I am wondering if you can help me with a
                            problem I've been having.</div>
                        <div class="small text-gray-500">Emily Fowler · 58m</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_2.svg"
                            alt="...">
                        <div class="status-indicator"></div>
                    </div>
                    <div>
                        <div class="text-truncate">I have the photos that you ordered last month, how
                            would you like them sent to you?</div>
                        <div class="small text-gray-500">Jae Chun · 1d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="img/undraw_profile_3.svg"
                            alt="...">
                        <div class="status-indicator bg-warning"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Last month's report looks great, I am very happy with
                            the progress so far, keep up the good work!</div>
                        <div class="small text-gray-500">Morgan Alvarez · 2d</div>
                    </div>
                </a>
                <a class="dropdown-item d-flex align-items-center" href="#">
                    <div class="dropdown-list-image mr-3">
                        <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60"
                            alt="...">
                        <div class="status-indicator bg-success"></div>
                    </div>
                    <div>
                        <div class="text-truncate">Am I a good boy? The reason I ask is because someone
                            told me that people say this to all dogs, even if they aren't good...</div>
                        <div class="small text-gray-500">Chicken the Dog · 2w</div>
                    </div>
                </a>
                <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
            </div>
        </li>

        <div class="topbar-divider d-none d-sm-block"></div>

        <!-- Nav Item - User Information -->
        <li class="nav-item dropdown no-arrow">
            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{request.user.full_name}}</span>
                <img class="img-profile rounded-circle"
                    src="{% static "img/undraw_profile.svg" %}">
            </a>
            <!-- Dropdown - User Information -->
            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profile
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                    Settings
                </a>
                <a class="dropdown-item" href="#">
                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                    Activity Log
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url "UserAuth:logout" %}" data-toggle="modal" data-target="#logoutModal">
                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                    Logout
                </a>
            </div>
        </li>

    </ul>

</nav>
<!-- End of Topbar -->